### ISSUE TITLE
Add example to handle null and missing property

### ISSUE THREAD

**Issue by nilsschmidthamburg** [wpanas/jackson-default-enum#1]
Would be really nice to have a solution for the following two examples: 

	println(App.handle("""{}"""))
	println(App.handle("""{"color": null}"""))

Do you have an idea how to handle this in a nice way?

**Comment by wpanas** [comment]
Great idea! I'll update my solution

**Comment by nilsschmidthamburg** [comment]
Well, I did figure out a solution using a custom `JsonDeserializer`, but it's far from optimal and not as concise as your original version with `JsonEnumDefaultValue`

```
@JsonDeserialize(using = ColorEnumDeserializer::class)
enum class Color {
	RED, GREEN, BLUE,

	@JsonEnumDefaultValue
	UNKNOWN
}

class ColorEnumDeserializer : StdDeserializer<Color>(Color::class.java) {
	override fun deserialize(p: JsonParser?, ctxt: DeserializationContext?): Color {
		return Color.values().firstOrNull { it.name ==  p?.valueAsString} ?: Color.UNKNOWN
	}

	override fun getNullValue(ctxt: DeserializationContext ) : Color {
		return Color.UNKNOWN;
	}
}
```

**Comment by wpanas** [comment]
It can be done better. I plan to code it through weekend.

**Comment by wpanas** [comment]
I fixed it. Hope it helps ;)

**Comment by wpanas** [comment]
I updated the article as well
